# Generated by Django 6.0 on 2025-12-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Welcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="/welcome/slash.jpg", upload_to="welcome"
                    ),
                ),
                ("order", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
        ),
    ]
