# Generated by Django 6.0 on 2025-12-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("usr_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("state", models.BooleanField()),
                ("is_fixed", models.BooleanField(default=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="daily.user"
                    ),
                ),
            ],
        ),
    ]
