# Generated by Django 6.0 on 2025-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0002_user_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="end",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="start",
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_fixed",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="state",
            field=models.BooleanField(default=False),
        ),
    ]
