# Generated by Django 6.0 on 2025-12-17 16:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0003_remove_plan_end_remove_plan_start_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=100)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(default=datetime.datetime.now)),
                ("duration", models.DurationField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="daily.user"
                    ),
                ),
            ],
        ),
    ]
