# Generated by Django 6.0 on 2025-12-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0004_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="duration",
        ),
    ]
