# Generated by Django 6.0 on 2025-12-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0005_remove_record_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="upload",
            field=models.BooleanField(default=False),
        ),
    ]
