# Generated by Django 6.0 on 2025-12-17 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0006_record_upload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Welcome",
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="record",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="usr_name",
        ),
        migrations.AddField(
            model_name="user",
            name="openid",
            field=models.CharField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="record",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
