# Generated by Django 6.0 on 2025-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0007_delete_welcome_rename_user_id_plan_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
        migrations.AddField(
            model_name="user",
            name="usr_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="openid",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
